stages:
  - docker

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind   
  script:
    - cp -r ./app ./docker/
    - cd docker
    - docker login -u gitlab-ci -p $DOCKER_REGISTRY_PASSWORD docker.luoja.fr
    - docker build -t mimir .
    - docker tag mimir docker.luoja.fr/mimir
    - docker push docker.luoja.fr/mimir